import { Navbar } from "@/components/Navbar";
import "./globals.css";
import { Roboto, Source_Sans_3 } from "next/font/google";
import { SocialMedia } from "@/components/SocialMedia";

const Source_Sans = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-source",
});

export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Source_Sans.className}>
        <Navbar />
        <div className="absolute mt-36 mob:hidden tablet:hidden pc:flex">
          <SocialMedia tailwind="flex flex-col bg-white p-4 gap-7 w-fit" isFooter={false}/>
        </div>
        {children}
      </body>
    </html>
  );
}
