export const skills = [
  { name: "HTML", link: "" },
  { name: "CSS", link: "" },
  { name: "Tailwind", link: "" },
  { name: "Styled Components", link: "" },
  { name: "JavaScript", link: "" },
  { name: "Typescript", link: "" },
  { name: "React", link: "" },
  { name: "Next.Js", link: "" },
  { name: "Git", link: "" },
  { name: "SEO", link: "" },
  { name: "Sanity", link: "" },
  { name: "Prisma", link: "" },
  { name: "Rest API", link: "" },
  { name: "Context API", link: "" },
  { name: "Design System", link: "" },
  { name: "Storybook", link: "" },
  { name: "Stripe", link: "" },
  { name: "GraphQL", link: "" },
];
